In [35]:
import pandas as pd
import numpy as np

In [86]:
df = pd.read_table('docword.kos.txt', delim_whitespace=True, names=('d', 'w', 'count'), skiprows = 3)

In [87]:
t = 10
w = 6906
d = 3430

def number_of_words():
    a = np.random.uniform(low=0.0, high=1.0, size=w)
    a = a / a.sum()
    return a

def number_of_themes():
    a = np.random.uniform(low=0.0, high=1.0, size=t)
    a = a / a.sum()
    return a

In [88]:
fi = number_of_words()
for i in range(t-1):
    fi = np.vstack([fi, number_of_words()])

tetta = number_of_themes()
for i in range(d-1):
    tetta = np.vstack([tetta, number_of_themes()])

In [89]:
fi = np.transpose(fi)
tetta = np.transpose(tetta)

In [90]:
x = []
for i in xrange(3430):
    x.append([])

In [91]:
df.sort_values(by=['w'], inplace = True)
df.reset_index(drop=True, inplace=True)

In [92]:
y = []
d = 1
k = 0
y.append([])
for i in df['w']:
    if i == d:
        y[d-1].append((df['d'][k],df['count'][k]))
        x[df['d'][k]-1].append((d-1, len(y[d-1])-1, df['count'][k]))
    else:
        d = d+1
        y.append([])
        y[d-1].append((df['d'][k],df['count'][k]))
        x[df['d'][k]-1].append((d-1, len(y[d-1])-1, df['count'][k]))
    k=k+1

In [93]:
for i in xrange(1):
    print i
    A = []
    for w in xrange(len(y)):
        A.append([])
        for d in xrange(len(y[w])):
            A[w].append([])
            z = 0
            for t in xrange(10):
                z = z + fi[w][t] * tetta[t][y[w][d][0]-1]
            for t in xrange(10):
                A[w][d].append(fi[w][t] * tetta[t][y[w][d][0]-1] / z)

    summa_po_slovam = []
    summa_po_slovam_i_temam = []
    for t in xrange(10):
        summa_po_slovam.append([])
        k = 0
        for w in xrange(len(y)):
            z = 0
            for d in xrange(len(y[w])):
                z = z + y[w][d][1] * A[w][d][t]
            summa_po_slovam[t].append(z)
            k = k + z
        summa_po_slovam_i_temam.append(k)

    for t in xrange(10):
        for w in xrange(len(y)):
            fi[w][t] = summa_po_slovam[t][w] / summa_po_slovam_i_temam[t]

    for t in xrange(10):
        for d in xrange(len(x)):
            z = 0
            for w in xrange(len(x[d])):
                z = z + x[d][w][2] * A[x[d][w][0]][x[d][w][1]][t]
            tetta[t][d] = z / 3430

0


In [57]:
for i in xrange(10):
    ind = np.argpartition(tetta[i], -10)[-10:]
    print ind

[3356 1708 2544 1101 3387 1149 1104 1395 1831 3219]
[1862 2025 2544 2740 1400 1603 2519 3352 1849 2349]
[1567  556 1707 2323 2538  479  189 1571 1738 1046]
[ 499 3049   22 1705 1541 1641 2963 1586 2945  880]
[2434 2354 2384 2063 1948 2043 1932 1952 1954 2540]
[2302 1437  388 2702 2778 1593  294 1767 2994 2655]
[ 411  229  723 1610 1629 1678  203  400 1769 3401]
[3087 1196 1623 2843 2851 1287  404 2730 2218   49]
[2690 3410 2037  594 2148   31 1517  231  619 2278]
[ 560 1664 1256 1533  895 1054 1294 1036  678  929]


In [94]:
fi_transpose = np.transpose(fi)
for i in xrange(10):
    ind1 = np.argpartition(fi_transpose[i], -20)[-20:]
    print ind1

[1095 2029 3419 3281 3857   88 4940 2639 4493 6295 3004 6661  840 4631 4734
 1579 6688 1665 4195 6658]
[2702 1579 4493 4441 6661  846 5895 3857 4634 4496 4760 4631 6295 1663 3419
 3281 4195  840  878 3004]
[4496 4092 4441 5551 4195 2012 1663 5890 4142 6688 4940 3857 4760 1665 2639
 4631  840 3281 3419 3004]
[6688 6661  237 4760 4940 2029 3349 4496 6295 2639 5551 4734 1663 1579  840
 6658 3419 5185 4493 4631]
[6658 4631 4634 4142 1665 4496 4493 3281 5184 4734   88 2029 1579 6295  840
 3004 6688 4195 1663 3419]
[4760 2718  840 2012 5895 4631 4441 1665 2639  878 5551 3004 3281 3857 4734
 3419 5185 4195 2029 1663]
[4941  846 5184 5551 2702 4493 1663 4940 1665  878 3281 4631 3004 2639 4195
 5890 5185  840 6688 3419]
[5185 4626 5895 6295 1665 3281 4493 5890 4634 4631 4760 1579 2029 2639 6658
 4195 4441  840  878 5551]
[4940 5895 3857 6658 5184  846 5185  840   88  878 3419 2030 3281 5890 6661
 6688 4634 4734 1663 5551]
[4246  892 4941 4634 4626   88 3004 5184 4734  840 5185 2029 1663 4195 58

In [95]:
df = pd.read_table('vocab.kos.txt', delim_whitespace=True, names=('w'))
ind1 = np.argpartition(fi_transpose[1], -20)[-20:]

In [78]:
for i in xrange(6906):
    for j in xrange(len(ind)):
        if i == ind[j]:
            print df['w'][i]

account
bush
contact
election
electoral
experience
general
governor
house
kerry
november
poll
polls
primary
republicans
senate
sunzoo
vote
voter
voting


In [96]:
for i in xrange(6906):
    for j in xrange(len(ind1)):
        if i == ind1[j]:
            print df['w'][i]

bush
bushs
campaign
dean
democratic
gop
house
iraq
kerry
media
november
party
people
percent
poll
polls
primary
states
time
voters
